#!/usr/bin/perl

use strict;
use warnings;
use 5.010;

use Getopt::Long;
use Pod::Usage;
use meon::Web::Search;

exit main();

sub main {
    my $help;
    my $dst_domain;
    GetOptions(
        'help|h'       => \$help,
        'hostname=s'   => \$dst_domain,
    ) or pod2usage;
    pod2usage if $help;
    pod2usage unless defined $dst_domain;

    my $mws = meon::Web::Search->new(
        hostname => $dst_domain,
    );

    use Data::Dumper; print "dump> ", Dumper([
        $mws->osearch_records,
    ]), "\n";


    return 0;
}

=head1 NAME

meon-web-generate-opensearch - generate opensearch search data

=head1 SYNOPSIS

    meon-web-generate-opensearch --hostname domain
        --hostname domain   domain of the web to generate search index

=head1 DESCRIPTION


=cut
